export function set_entity_data() {
  return {
    runtime_entity_id: 1n,
    metadata: [
      {
        key: "flags",
        type: "long",
        value: {
          _value: 844424930656256n,
          onfire: false,
          sneaking: false,
          riding: false,
          sprinting: false,
          action: false,
          invisible: false,
          tempted: false,
          inlove: false,
          saddled: false,
          powered: false,
          ignited: false,
          baby: false,
          converting: false,
          critical: false,
          can_show_nametag: false,
          always_show_nametag: false,
          no_ai: false,
          silent: false,
          wallclimbing: false,
          can_climb: true,
          swimmer: false,
          can_fly: false,
          walker: false,
          resting: false,
          sitting: false,
          angry: false,
          interested: false,
          charged: false,
          tamed: false,
          orphaned: false,
          leashed: false,
          sheared: false,
          gliding: false,
          elder: false,
          moving: false,
          breathing: false,
          chested: false,
          stackable: false,
          showbase: false,
          rearing: false,
          vibrating: false,
          idling: false,
          evoker_spell: false,
          charge_attack: false,
          wasd_controlled: false,
          can_power_jump: false,
          can_dash: false,
          linger: false,
          has_collision: true,
          affected_by_gravity: true,
          fire_immune: false,
          dancing: false,
          enchanted: false,
          show_trident_rope: false,
          container_private: false,
          transforming: false,
          spin_attack: false,
          swimming: false,
          bribed: false,
          pregnant: false,
          laying_egg: false,
          rider_can_pick: false,
          transition_sitting: false,
          eating: false,
          laying_down: false,
        },
      },
      {
        key: "health",
        type: "int",
        value: 1,
      },
      {
        key: "variant",
        type: "int",
        value: 0,
      },
      {
        key: "color",
        type: "byte",
        value: 0,
      },
      {
        key: "nametag",
        type: "string",
        value: "Sunny",
      },
      {
        key: "owner_eid",
        type: "long",
        value: -1n,
      },
      {
        key: "target_eid",
        type: "long",
        value: 0n,
      },
      {
        key: "air",
        type: "short",
        value: 300,
      },
      {
        key: "charge_amount",
        type: "byte",
        value: 0,
      },
      {
        key: "player_flags",
        type: "byte",
        value: 0,
      },
      {
        key: "player_index",
        type: "int",
        value: 1,
      },
      {
        key: "player_bed_position",
        type: "vec3i",
        value: {
          x: 0,
          y: 0,
          z: 0,
        },
      },
      {
        key: "lead_holder_eid",
        type: "long",
        value: -1n,
      },
      {
        key: "interactive_tag",
        type: "byte",
        value: 0,
      },
      {
        key: "max_airdata_max_air",
        type: "short",
        value: 300,
      },
      {
        key: "mark_variant",
        type: "int",
        value: 0,
      },
      {
        key: "container_type",
        type: "byte",
        value: 0,
      },
      {
        key: "container_base_size",
        type: "int",
        value: 0,
      },
      {
        key: "container_extra_slots_per_strength",
        type: "int",
        value: 0,
      },
      {
        key: "rider_rotation_locked",
        type: "byte",
        value: 0,
      },
      {
        key: "rider_max_rotation",
        type: "float",
        value: 0,
      },
      {
        key: "rider_min_rotation",
        type: "byte",
        value: 0,
      },
      {
        key: "rider_seat_rotation_offset",
        type: "float",
        value: 0,
      },
      {
        key: "has_command_block",
        type: "byte",
        value: 0,
      },
      {
        key: "command_block_command",
        type: "string",
        value: "",
      },
      {
        key: "command_block_last_output",
        type: "string",
        value: "",
      },
      {
        key: "command_block_track_output",
        type: "byte",
        value: 1,
      },
      {
        key: "strength",
        type: "int",
        value: 0,
      },
      {
        key: "max_strength",
        type: "int",
        value: 0,
      },
      {
        key: "evoker_spell_casting_color",
        type: "int",
        value: 0,
      },
      {
        key: "limited_life",
        type: "int",
        value: -1,
      },
      {
        key: "always_show_nametag",
        type: "byte",
        value: 1,
      },
      {
        key: "color_2",
        type: "byte",
        value: 0,
      },
      {
        key: "score_tag",
        type: "string",
        value: "",
      },
      {
        key: "agent",
        type: "long",
        value: -1n,
      },
      {
        key: "eating_counter",
        type: "int",
        value: 0,
      },
      {
        key: "flags_extended",
        type: "long",
        value: {
          _value: 35184405643264n,
          sneezing: false,
          trusting: false,
          rolling: false,
          scared: false,
          in_scaffolding: false,
          over_scaffolding: false,
          fall_through_scaffolding: false,
          blocking: false,
          transition_blocking: false,
          blocked_using_shield: false,
          blocked_using_damaged_shield: false,
          sleeping: false,
          wants_to_wake: false,
          trade_interest: false,
          door_breaker: false,
          breaking_obstruction: false,
          door_opener: false,
          illager_captain: false,
          stunned: false,
          roaring: false,
          delayed_attacking: false,
          avoiding_mobs: false,
          avoiding_block: false,
          facing_target_to_range_attack: false,
          hidden_when_invisible: false,
          is_in_ui: true,
          stalking: false,
          emoting: false,
          celebrating: false,
          admiring: false,
          celebrating_special: false,
          unknown95: false,
          ram_attack: false,
          playing_dead: false,
          in_ascendable_block: false,
          over_descendable_block: false,
          croaking: false,
          eat_mob: false,
          jump_goal_jump: false,
          emerging: false,
          sniffing: false,
          digging: false,
          sonic_boom: false,
          has_dash_cooldown: false,
          push_towards_closest_space: false,
          scenting: true,
          rising: false,
          feeling_happy: false,
          searching: false,
          crawling: false,
          timer_flag_1: false,
          timer_flag_2: false,
          timer_flag_3: false,
          body_rotation_blocked: false,
          render_when_invisible: false,
          body_rotation_axis_aligned: false,
          collidable: false,
          wasd_air_controlled: false,
          does_server_auth_only_dismount: false,
          body_rotation_always_follows_head: false,
          can_use_vertical_movement_action: false,
          rotation_locked_to_vehicle: false,
        },
      },
      {
        key: "interact_text",
        type: "string",
        value: "",
      },
      {
        key: "trade_tier",
        type: "int",
        value: 0,
      },
      {
        key: "max_trade_tier",
        type: "int",
        value: 0,
      },
      {
        key: "trade_experience",
        type: "int",
        value: 0,
      },
      {
        key: "skin_id",
        type: "int",
        value: 0,
      },
      {
        key: "command_block_tick_delay",
        type: "int",
        value: 3,
      },
      {
        key: "command_block_execute_on_first_tick",
        type: "byte",
        value: 1,
      },
      {
        key: "ambient_sound_interval",
        type: "float",
        value: 8,
      },
      {
        key: "ambient_sound_interval_range",
        type: "float",
        value: 16,
      },
      {
        key: "ambient_sound_event_name",
        type: "string",
        value: "ambient",
      },
      {
        key: "fall_damage_multiplier",
        type: "float",
        value: 1,
      },
      {
        key: "can_ride_target",
        type: "byte",
        value: 0,
      },
      {
        key: "low_tier_cured_discount",
        type: "int",
        value: 0,
      },
      {
        key: "high_tier_cured_discount",
        type: "int",
        value: 0,
      },
      {
        key: "nearby_cured_discount",
        type: "int",
        value: 0,
      },
      {
        key: "nearby_cured_discount_timestamp",
        type: "int",
        value: 0,
      },
      {
        key: "hitbox",
        type: "compound",
        value: {
          type: "compound",
          name: "",
          value: {},
        },
      },
      {
        key: "is_buoyant",
        type: "byte",
        value: 0,
      },
      {
        key: "freezing_effect_strength",
        type: "float",
        value: 0,
      },
      {
        key: "movement_sound_distance_offset",
        type: "float",
        value: 1,
      },
      {
        key: "heartbeat_interval_ticks",
        type: "int",
        value: 20,
      },
      {
        key: "heartbeat_sound_event",
        type: "int",
        value: 578,
      },
      {
        key: "player_last_death_position",
        type: "vec3i",
        value: {
          x: 0,
          y: 0,
          z: 0,
        },
      },
      {
        key: "player_last_death_dimension",
        type: "int",
        value: 0,
      },
      {
        key: "player_has_died",
        type: "byte",
        value: 0,
      },
      {
        key: "collision_box",
        type: "vec3f",
        value: {
          x: 0.6000000238418579,
          y: 1.7999999523162842,
          z: 0,
        },
      },
      {
        key: "visible_mob_effects",
        type: "long",
        value: 0n,
      },
      {
        key: "filtered_name",
        type: "string",
        value: "",
      },
      {
        key: "bed_enter_position",
        type: "vec3f",
        value: {
          x: 0,
          y: 0,
          z: 0,
        },
      },
      {
        key: "seat_third_person_camera_radius",
        type: "float",
        value: 0,
      },
      {
        key: "seat_camera_relax_distance_smoothing",
        type: "float",
        value: 0,
      },
    ],
    properties: {
      ints: [],
      floats: [],
    },
    tick: 0n,
  };
}
