export function camera_presets() {
  return {
    presets: [
      {
        name: "minecraft:first_person",
        parent: "",
        position: {
          x: undefined,
          y: undefined,
          z: undefined,
        },
        rotation: {
          x: undefined,
          y: undefined,
        },
        rotation_speed: undefined,
        snap_to_target: undefined,
        horizontal_rotation_limit: undefined,
        vertical_rotation_limit: undefined,
        continue_targeting: undefined,
        tracking_radius: undefined,
        offset: undefined,
        entity_offset: undefined,
        radius: undefined,
        yaw_limit_min: undefined,
        yaw_limit_max: undefined,
        audio_listener: undefined,
        player_effects: undefined,
        aim_assist: undefined,
        control_scheme: undefined,
      },
      {
        name: "minecraft:fixed_boom",
        parent: "",
        position: {
          x: undefined,
          y: undefined,
          z: undefined,
        },
        rotation: {
          x: undefined,
          y: undefined,
        },
        rotation_speed: undefined,
        snap_to_target: undefined,
        horizontal_rotation_limit: undefined,
        vertical_rotation_limit: undefined,
        continue_targeting: undefined,
        tracking_radius: undefined,
        offset: {
          x: 0,
          z: 0,
        },
        entity_offset: {
          x: 0,
          y: 0,
          z: 0,
        },
        radius: undefined,
        yaw_limit_min: undefined,
        yaw_limit_max: undefined,
        audio_listener: undefined,
        player_effects: undefined,
        aim_assist: undefined,
        control_scheme: undefined,
      },
      {
        name: "minecraft:follow_orbit",
        parent: "",
        position: {
          x: undefined,
          y: undefined,
          z: undefined,
        },
        rotation: {
          x: undefined,
          y: undefined,
        },
        rotation_speed: undefined,
        snap_to_target: undefined,
        horizontal_rotation_limit: undefined,
        vertical_rotation_limit: undefined,
        continue_targeting: undefined,
        tracking_radius: undefined,
        offset: {
          x: 0,
          z: 0,
        },
        entity_offset: {
          x: 0,
          y: 0,
          z: 0,
        },
        radius: 10,
        yaw_limit_min: undefined,
        yaw_limit_max: undefined,
        audio_listener: undefined,
        player_effects: undefined,
        aim_assist: undefined,
        control_scheme: undefined,
      },
      {
        name: "minecraft:free",
        parent: "",
        position: {
          x: 0,
          y: 0,
          z: 0,
        },
        rotation: {
          x: 0,
          y: 0,
        },
        rotation_speed: undefined,
        snap_to_target: undefined,
        horizontal_rotation_limit: undefined,
        vertical_rotation_limit: undefined,
        continue_targeting: undefined,
        tracking_radius: undefined,
        offset: undefined,
        entity_offset: undefined,
        radius: undefined,
        yaw_limit_min: undefined,
        yaw_limit_max: undefined,
        audio_listener: undefined,
        player_effects: undefined,
        aim_assist: undefined,
        control_scheme: undefined,
      },
      {
        name: "minecraft:third_person",
        parent: "",
        position: {
          x: undefined,
          y: undefined,
          z: undefined,
        },
        rotation: {
          x: undefined,
          y: undefined,
        },
        rotation_speed: undefined,
        snap_to_target: undefined,
        horizontal_rotation_limit: undefined,
        vertical_rotation_limit: undefined,
        continue_targeting: undefined,
        tracking_radius: undefined,
        offset: undefined,
        entity_offset: undefined,
        radius: undefined,
        yaw_limit_min: undefined,
        yaw_limit_max: undefined,
        audio_listener: undefined,
        player_effects: undefined,
        aim_assist: undefined,
        control_scheme: undefined,
      },
      {
        name: "minecraft:third_person_front",
        parent: "",
        position: {
          x: undefined,
          y: undefined,
          z: undefined,
        },
        rotation: {
          x: undefined,
          y: undefined,
        },
        rotation_speed: undefined,
        snap_to_target: undefined,
        horizontal_rotation_limit: undefined,
        vertical_rotation_limit: undefined,
        continue_targeting: undefined,
        tracking_radius: undefined,
        offset: undefined,
        entity_offset: undefined,
        radius: undefined,
        yaw_limit_min: undefined,
        yaw_limit_max: undefined,
        audio_listener: undefined,
        player_effects: undefined,
        aim_assist: undefined,
        control_scheme: undefined,
      },
    ],
  };
}
