export function game_rules_changed() {
  return {
    rules: [
      {
        name: "commandBlockOutput",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doDayLightCycle",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doEntityDrops",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doFireTick",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "recipesUnlock",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doLimitedCrafting",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "doMobLoot",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doMobSpawning",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "doTileDrops",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doWeatherCycle",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "drowningDamage",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "fallDamage",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "fireDamage",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "keepInventory",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "mobGriefing",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "pvp",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "showCoordinates",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "locatorBar",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "showDaysPlayed",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "naturalRegeneration",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "tntExplodes",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "sendCommandFeedback",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "maxCommandChainLength",
        editable: true,
        type: "int",
        value: 65535,
      },
      {
        name: "doInsomnia",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "commandBlocksEnabled",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "randomTickSpeed",
        editable: true,
        type: "int",
        value: 1,
      },
      {
        name: "doImmediateRespawn",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "showDeathMessages",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "functionCommandLimit",
        editable: true,
        type: "int",
        value: 10000,
      },
      {
        name: "spawnRadius",
        editable: true,
        type: "int",
        value: 10,
      },
      {
        name: "showTags",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "freezeDamage",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "respawnBlocksExplode",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "showBorderEffect",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "showRecipeMessages",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "playersSleepingPercentage",
        editable: true,
        type: "int",
        value: 100,
      },
      {
        name: "projectilesCanBreakBlocks",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "tntExplosionDropDecay",
        editable: true,
        type: "bool",
        value: false,
      },
    ],
  };
}
