export function start_game() {
  return {
    entity_id: -81604378623n,
    runtime_entity_id: 1n,
    player_gamemode: "fallback",
    player_position: {
      x: 28.6392879486084,
      y: 1.620010495185852,
      z: 8.522401809692383,
    },
    rotation: {
      x: 2.1258544921875,
      z: 146.8487548828125,
    },
    seed: [3139436260, 3938430568],
    biome_type: 0,
    biome_name: "minecraft:plains",
    dimension: "overworld",
    generator: 2,
    world_gamemode: "survival",
    hardcore: false,
    difficulty: 0,
    spawn_position: {
      x: 0,
      y: 32767,
      z: 0,
    },
    achievements_disabled: true,
    editor_world_type: "not_editor",
    created_in_editor: false,
    exported_from_editor: false,
    day_cycle_stop_time: 2028767,
    edu_offer: 0,
    edu_features_enabled: false,
    edu_product_uuid: "",
    rain_level: 0,
    lightning_level: 0,
    has_confirmed_platform_locked_content: false,
    is_multiplayer: true,
    broadcast_to_lan: true,
    xbox_live_broadcast_mode: 6,
    platform_broadcast_mode: 6,
    enable_commands: true,
    is_texturepacks_required: false,
    gamerules: [
      {
        name: "commandBlockOutput",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doDayLightCycle",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doEntityDrops",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doFireTick",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "recipesUnlock",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doLimitedCrafting",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "doMobLoot",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doMobSpawning",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "doTileDrops",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "doWeatherCycle",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "drowningDamage",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "fallDamage",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "fireDamage",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "keepInventory",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "mobGriefing",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "pvp",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "showCoordinates",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "locatorBar",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "showDaysPlayed",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "naturalRegeneration",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "tntExplodes",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "sendCommandFeedback",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "maxCommandChainLength",
        editable: true,
        type: "int",
        value: 131070,
      },
      {
        name: "doInsomnia",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "commandBlocksEnabled",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "randomTickSpeed",
        editable: true,
        type: "int",
        value: 2,
      },
      {
        name: "doImmediateRespawn",
        editable: true,
        type: "bool",
        value: false,
      },
      {
        name: "showDeathMessages",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "functionCommandLimit",
        editable: true,
        type: "int",
        value: 20000,
      },
      {
        name: "spawnRadius",
        editable: true,
        type: "int",
        value: 20,
      },
      {
        name: "showTags",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "freezeDamage",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "respawnBlocksExplode",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "showBorderEffect",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "showRecipeMessages",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "playersSleepingPercentage",
        editable: true,
        type: "int",
        value: 200,
      },
      {
        name: "projectilesCanBreakBlocks",
        editable: true,
        type: "bool",
        value: true,
      },
      {
        name: "tntExplosionDropDecay",
        editable: true,
        type: "bool",
        value: false,
      },
    ],
    experiments: [],
    experiments_previously_used: false,
    bonus_chest: false,
    map_enabled: false,
    permission_level: "operator",
    server_chunk_tick_range: 4,
    has_locked_behavior_pack: false,
    has_locked_resource_pack: false,
    is_from_locked_world_template: false,
    msa_gamertags_only: true,
    is_from_world_template: false,
    is_world_template_option_locked: false,
    only_spawn_v1_villagers: false,
    persona_disabled: false,
    custom_skins_disabled: false,
    emote_chat_muted: false,
    game_version: "*",
    limited_world_width: 16,
    limited_world_length: 16,
    is_new_nether: false,
    edu_resource_uri: {
      button_name: "",
      link_uri: "",
    },
    experimental_gameplay_override: false,
    chat_restriction_level: "none",
    disable_player_interactions: false,
    server_identifier: "",
    world_identifier: "",
    scenario_identifier: "",
    owner_identifier: "",
    level_id: "Flat",
    world_name: "FLAT",
    premium_world_template_id: "00000000-0000-0000-0000-000000000000",
    is_trial: false,
    rewind_history_size: 40,
    server_authoritative_block_breaking: true,
    current_tick: [0, 2028756],
    enchantment_seed: 1421020395,
    block_properties: [],
    multiplayer_correlation_id: "<raknet>9587-f24d-1b81-0071",
    server_authoritative_inventory: true,
    engine: "1.21.130",
    property_data: {
      type: "compound",
      name: "",
      value: {},
    },
    block_pallette_checksum: [1988470248, 1905879201],
    world_template_id: "00000000-0000-0000-0000-000000000000",
    client_side_generation: false,
    block_network_ids_are_hashes: true,
    server_controlled_sound: true,
  };
}
