export function update_abilities() {
  return {
    entity_unique_id: [-19, 1],
    permission_level: "member",
    command_permission: "normal",
    abilities: [
      {
        type: "base",
        allowed: {
          _value: 1048575,
          build: true,
          mine: true,
          doors_and_switches: true,
          open_containers: true,
          attack_players: true,
          attack_mobs: true,
          operator_commands: true,
          teleport: true,
          invulnerable: true,
          flying: true,
          may_fly: true,
          instant_build: true,
          lightning: true,
          fly_speed: true,
          walk_speed: true,
          muted: true,
          world_builder: true,
          no_clip: true,
          privileged_builder: true,
          vertical_fly_speed: true,
          count: false,
        },
        enabled: {
          _value: 63,
          build: true,
          mine: true,
          doors_and_switches: true,
          open_containers: true,
          attack_players: true,
          attack_mobs: true,
          operator_commands: false,
          teleport: false,
          invulnerable: false,
          flying: false,
          may_fly: false,
          instant_build: false,
          lightning: false,
          fly_speed: false,
          walk_speed: false,
          muted: false,
          world_builder: false,
          no_clip: false,
          privileged_builder: false,
          vertical_fly_speed: false,
          count: false,
        },
        fly_speed: 0.05000000074505806,
        vertical_fly_speed: 1,
        walk_speed: 0.10000000149011612,
      },
    ],
  };
}
